ERROR - 2023-03-01 13:43:45 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'e_pemas' in C:\xampp2\htdocs\epemas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp2\htdocs\epemas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'e_pemas', 3306, '', 0)
#1 C:\xampp2\htdocs\epemas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp2\htdocs\epemas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp2\htdocs\epemas\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp2\htdocs\epemas\app\Models\UserModel.php(57): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp2\htdocs\epemas\app\Controllers\Login.php(61): App\Models\UserModel->verify_user('tfsid', '$2y$10$JxOWE84j...')
#6 C:\xampp2\htdocs\epemas\system\CodeIgniter.php(934): App\Controllers\Login->auth()
#7 C:\xampp2\htdocs\epemas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp2\htdocs\epemas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp2\htdocs\epemas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp2\htdocs\epemas\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp2\\htdoc...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'e_pemas' in C:\xampp2\htdocs\epemas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp2\htdocs\epemas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp2\htdocs\epemas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp2\htdocs\epemas\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp2\htdocs\epemas\app\Models\UserModel.php(57): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp2\htdocs\epemas\app\Controllers\Login.php(61): App\Models\UserModel->verify_user('tfsid', '$2y$10$JxOWE84j...')
#5 C:\xampp2\htdocs\epemas\system\CodeIgniter.php(934): App\Controllers\Login->auth()
#6 C:\xampp2\htdocs\epemas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#7 C:\xampp2\htdocs\epemas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp2\htdocs\epemas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp2\htdocs\epemas\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp2\\htdoc...')
#10 {main}
CRITICAL - 2023-03-01 13:43:45 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'e_pemas'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `masyarakat`
WHERE `Username` = :Username:
AND `Password` = :Password:', [...], false)
 3 APPPATH\Models\UserModel.php(57): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Login.php(61): App\Models\UserModel->verify_user('tfsid', '$2y$10$JxOWE84jWkMkkm6a6EMqDe3/r')
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Login->auth()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
INFO - 2023-03-01 13:44:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
